version: '3.7'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v19.1.4
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "always"
    volumes:
      - ./data/cockroach:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
  nakama:
    image: heroiclabs/nakama:2.14.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
        exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257 --logger.level DEBUG --session.token_expiry_sec 60
    restart: "always"
    links:
      - "cockroachdb:db"
    depends_on:
      - cockroachdb
    volumes:
      - ./data/nakama:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5


