name: nakama_client
description: Client library for nakama server
version: 0.1.1
authors:  
  - dertom <thomas.trocha@gmail.com>
  - devsensa <person.sensa@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  protobuf: ^0.14.3
  fixnum: ^0.10.9
  grpc: ^2.1.2
  meta: ^1.1.7

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
