////@Getter
////@EqualsAndHashCode
////@ToString
////@NoArgsConstructor(access = AccessLevel.PACKAGE)
/**
 * The matchmaker ticket received from the server.
 */
class MatchmakerTicket {
  /**
   * The ticket generated by the matchmaker.
   */
  String ticket;
}
